# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        date

# Optional features
show_related_posts: true

# Disqus
disqus:
    shortname: 'carolinabigonha'

# Setup
title:            Carolina Bigonha
url:              http://carolinabigonha.com
tagline: 		  ' | Blog'
description: 	  'Co-fundadora e Product Onwer da <a href="http://zahpee.com">zahpee</a>.'
paginate:         5
baseurl:          /
author:
  name:           Carolina Bigonha
  url:            https://twitter.com/carolinabigonha
  email:          carolinabigonha@gmail.com
